name: Unclebob
favicon: null
layout_spectrum: 0.242643425706774
typography_spectrum: 0.7754842105787247
title: Mobile Apps with Uncle Bob
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#fed807'
    - '#afafaf'
    - '#505050'
  brandStrength: 0.45348620950244367
  lightness: 0.5822997493669391
  saturation: 0.32348249084316194
  rhythmicContrast: 0.9492091140709817
purpose: []
